### ISSUE TITLE
Usage in ccnet-hipchat-v2-publisher

### ISSUE THREAD

**Issue by aolszowka** [sirkirby/hipchat.net#5]
Hi,

Thank you for this project!

I just wanted to drop a note to let you know this is being used in a project I've created for a custom [CruiseControl.NET Publisher to publish to HipChat](../../../aolszowka/ccnet-hipchat-v2-publisher) and was very useful. I've included a link to your license in the README.md, but if there is anything else I need to do please let me know!

**Comment by sirkirby** [comment]
NP, Great implementation! My original intention with the lib was to do something similar, essentially post notifications from my apps to various channels. I was also hoping to complete all of the 2.0 functionality, but just haven't gotten around to it yet.  I did have plans to use it in a universal windows app, hence the portable .NET api target, but just built the sample web app instead.

Please feel free to contribute any additional functionality you would like to have in the lib....PR's are very welcome.
